### ISSUE TITLE
Move and animate "Refresh All" ... "Restore..." buttons

### ISSUE THREAD

**Issue by dpharris** [openlcb/OpenLCB_Java#65] opened 2016-12-13 02:16 UTC
Can the four buttons be moved to the always visible bar where the "Read All" button is?  

Can the "Refresh All" and "Save Changes" buttons change colour to indicate something has changed?

**Comment by balazsracz** [comment] 2016-12-13 19:17
David,

thanks for flagging this.
I have already started working on it https://github.com/openlcb/OpenLCB_Java/commit/7f453a6fe20988fe619e238261da3792b02b7dfb#diff-db8575e4c24ce0b766d8d9f86883c5d4R134

There are some tricky issues around the nesting of JPanel objects and scrollbars that makes it more complicated than it sounds. Basically due to the split between the two codebases it was not possible to do this in one step and still get the interesting new features into 4.6:
- the "Read All" button and the respective footer is rendered by jmri.jar, while the new buttons (Save changed, backup, restore, etc) are rendered by openlcb.jar.
- there was no way to put the new openlcb buttons into the JMRI-rendered bar (no API for that)
- openlcb.jar cannot influence the rendering that JMRI does
- we cannot nest a scrollpane inside a scrollpane (it breaks scrolling by the mouse)
- due to the code freeze coming up to the 4.6 prod release it was undesired to make large changes.

So instead I focused on laying the foundation that will allow us to remove the Read All button in the first development release coming up. At that point I will be able to fix the bottom bar to be on the screen at all times.

On your other request (of coloring the buttons): I am not a fond of this idea. Generally coloring buttons breaks the look&feel of the UI and looks pretty kludgy therefore. It also is not guaranteed to work in different UIs, for example in the Max and GTK UI it would likely be broken.

What I can do is make the "Save changed" button be Disabled (grayed out) vs Enabled depending on whether you have any changed values. All look&feels have a native form of displaying a disabled button.

The "Refresh All" cannot be changed in a meaningful way, because it has no way of telling whether something changed on the node itself. "Refresh All" doesn't just discard all edited fields, it also reloads every field from the current value of the node. So pressing Refresh All makes sense even if you have not changed anything (but maybe someone else on a different computer did).

Balazs

**Comment by dpharris** [comment] 2016-12-14 00:07
Balazs --
Thanks ... all good and acceptable explanations.  You have made it so much
better already that these changes can wait :-)
David
PS -- the load speed is great.

**Comment by balazsracz** [comment] 2017-04-08 12:26
These are now moved into a single button bar that is always visible.

The save changed still needs an disable/enable feature when something is dirty.

**Comment by balazsracz** [comment] 2020-04-05 12:51
Duplicate of #147

**Closed by balazsracz** 2020-04-05 12:51 UTC
Labels: UI, enhancement
