### ISSUE TITLE
CDI pane cannot be opened again after closing the CDI pane

### ISSUE THREAD

**Issue by heikens** [openlcb/OpenLCB_Java#11] opened 2016-10-26 16:14 UTC
@balazsracz 
Opening the CDI pane can only be done once. After closing the CDI pane it cannot be opened again in the same session.

**Comment by balazsracz** [comment] 2016-10-27 15:37
Could you please post exact reproduction instructions? (I'm not sure what
you mean by "pane" for example). Sequence on where to click and what you
experienced. Also post log from the jmri log window please.

Thanks
Balazs

--
Sent from my mobile device

**Comment by heikens** [comment] 2016-10-27 15:47
Reproduction instructions:
- from the OpenLCB menu, click Configure Nodes;
- select a node which supports the CDI protocol;
- click on CDI, to open the CDI pane / window;
- now close that window;
- click on CDI from that same node again;
- no response, not opening the CDI window.

**Comment by heikens** [comment] 2016-10-27 15:53
Nothing appears in the jmri log during the last 3 actions from previous comment.
Now select another node, then re-select the non-responsive node does re-open the CDI.
Should it work that way?

Thanks,
Rob

**Comment by pabender** [comment] 2016-10-27 16:14
Rob,


On Thu, Oct 27, 2016 at 11:53 AM, Rob Heikens <notifications@github.com>
wrote:

> Nothing appears in the jmri log during the last 3 actions from previous
> comment.
> Now select another node, then re-select the non-responsive node does
> re-open the CDI.
> Should it work that way?
>
It isn't supposed to work that way.

I haven't noticed this exact behavior, and I've been busy with other things
the last couple of weeks,
so I haven't had a chance to dig into this again.

I don't know if the new code fixes this or not, but there was an issue with
partial loads of data that was resolved by the same select another node and
then select the original.

Paul

**Comment by balazsracz** [comment] 2016-10-27 22:49
I checked this. The problem is that the TreePane is abused in trying to make the individual lines act as "button"s, but the only callback that is available is fired when the selection changes.

Thus the customer needs to click on *any other line* and then can come back and click CDI again, but it is correct that right now clicking CDI when it is already highlighted has no effect.

There is a quick fix in clearing the selection immediately. The side effect of this fix however is that the user gets no visual feedback that their click has actually happened. This is a problem since we do not have a progress bar while we are loading the CDI.xml and it takes quite a bit of time usually.

I'll attach my fix here and you can comment on whether we should merge it or not.

**Comment by balazsracz** [comment] 2016-10-27 22:51
I'm not sure how to associate a pull request with an issue.

https://github.com/openlcb/OpenLCB_Java/pull/12

**Comment by heikens** [comment] 2016-10-28 08:47
The workaround is fine with me until we have some sort of progress bar in place. I prefer to be able to reselect the CDI from the TreePane directly without having to click something else first.

Thanks,
Rob

**Closed** 2016-10-28 10:29 UTC
